### ISSUE TITLE
Removing English Stop words on the Word Cloud

### ISSUE THREAD

**Issue by dn4086** [jdharrisnz/datorama-d3-word-cloud#1]
Hey Josh,
Is there any way to remove English stop words from the word cloud? The list of stop words can be found here.
https://gist.github.com/sebleier/554280

**Comment by jdharrisnz** [comment]
Hi Dan,

If you take a look at the [preferences](https://github.com/jdharrisnz/datorama-d3-word-cloud#preferences) section of the readme, it will tell you how to remove words. It's just a long space-separated string.

Thanks,
Josh
